---
  theme: none
  default_locale: pt
  addthis_pubid: "ra-4db0c70d4e7542c2"
  title: Itaca Project
  site_name: Itaca Project
  site_header: Itaca Project
  announcement_size: "910x200#"
  force_locale: "true"
