--- 
  theme: tidypresent
  default_locale: en
  addthis_pubid: "ra-4db0c70d4e7542c2"
  title: GAEB
  site_name: GAEB
  site_header: Gabinete de Alunos de Engenharia Biomédica da Universidade do Minho
  force_locale: "true"
