---
  theme: none
  default_locale: pt
  addthis_pubid: "ra-4db0c70d4e7542c2"
  title: "Partido Social Democrata - Guimarães"
  site_name: "Partido Social Democrata - Guimarães"
  site_header: "Partido Social Democrata - Guimarães"
  announcement_size: "1000x250#"
  force_locale: "true"
