--- 
  theme: hill
  default_locale: en
  addthis_pubid: "ra-4db0c70d4e7542c2"
  title: NECC
  site_name: NECC
  site_header: Núcleo de Estudantes de Ciências da Computação da Universidade do Minho
  force_locale: "true"
