--- 
  theme: boxyframe
  default_locale: en
  addthis_pubid: "ra-4db0c70d4e7542c2"
  title: NEBAUM
  site_name: NEBAUM
  site_header: Núcleo de Estudantes de Biologia Aplicada da Universidade do Minho
  force_locale: "true"
