---
  theme: none
  default_locale: pt
  title: Paris Português
  site_name: Paris Português
  site_header: Paris Português
  announcement_size: "648x180#"
  force_locale: "true"
  has_gallery: "true"
