---
  theme: none
  default_locale: pt
  addthis_pubid: "ra-4db0c70d4e7542c2"
  title: "Paris Português"
  site_name: "Paris Português"
  site_header: "Paris Português"
  announcement_size: "648x185#"
  force_locale: "true"
