--- 
  theme: redsign
  default_locale: en
  addthis_pubid: "ra-4db0c70d4e7542c2"
  title: NED
  site_name: NED
  site_header: Núcleo de Estudantes de Direito da Universidade de Coimbra
  force_locale: "true"