--- 
  theme: topster
  default_locale: en
  addthis_pubid: "ra-4db0c70d4e7542c2"
  title: GACCUM
  site_name: GACCUM
  site_header: Grupo de Alunos de Ciências da Comunicação da Universidade do Minho
  force_locale: "true"
